version: '3.7'
services:
  mord_zookeeper:
    image: zookeeper
    restart: always
    container_name: mord_zookeeper
    hostname: mord_zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1

  mord_kafka:
    image: wurstmeister/kafka
    container_name: mord_kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: [YOUR_IP]
      KAFKA_ZOOKEEPER_CONNECT: mord_zookeeper:2181
      KAFKA_CREATE_TOPICS: "user_update_2:1:1,user_deleted:1:1"
  
  mord_kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: mord_kafka_manager
    ports:
      - '9000:9000'
    environment:
      ZK_HOSTS: 'mord_zookeeper:2181'
      APPLICATION_SECRET: 'random-secret'
    command: -Dpidfile.path=/dev/null