basePath: /
definitions:
  domain.Account:
    properties:
      Balance:
        example: 40000
        type: integer
      Cpf:
        example: 00.00.111.11
        type: string
      CreatedAt:
        example: "2019-11-09T21:21:46+00:00"
        type: string
      id:
        example: "1"
        type: string
      name:
        example: Leo Messi
        type: string
    type: object
  domain.CharityMrys:
    properties:
      Amount:
        example: 40000
        type: integer
      CreatedAt:
        example: "2019-11-09T21:21:46+00:00"
        type: string
      Description:
        example: description
        type: string
      Month:
        example: 1
        type: integer
      Year:
        example: 2021
        type: integer
      id:
        example: "1"
        type: string
      name:
        example: Leo Messi
        type: string
    type: object
  domain.CharityMrysPagination:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.CharityMrys'
        type: array
      meta:
        $ref: '#/definitions/domain.MetaPagination'
    type: object
  domain.MetaPagination:
    properties:
      currentPage:
        type: integer
      offset:
        type: integer
      perPage:
        type: integer
      sort:
        type: string
      total:
        type: integer
      totalPage:
        type: integer
    type: object
  usecase.CreateBulkCharityMrysInput:
    properties:
      amount:
        example: 40000
        type: integer
      description:
        example: description
        type: string
      id:
        example: "1"
        type: string
      month_from:
        example: 2
        type: integer
      month_to:
        example: 10
        type: integer
      name:
        example: Leo Messi
        type: string
      year:
        example: 2021
        type: integer
    required:
    - amount
    - month_from
    - month_to
    - name
    - year
    type: object
host: localhost:8000/vhry/data/
info:
  contact:
    email: felixanthony1996.fa@gmail.com
  description: Data API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Data API
  version: "1.0"
paths:
  /v1/accounts:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      security:
      - ApiKeyAuth: []
      summary: Find All Accounts
      tags:
      - Accounts
    post:
      consumes:
      - application/json
      description: Create account
      parameters:
      - description: Create account
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Account'
      summary: Create account
      tags:
      - Accounts
  /v1/accounts/{account_id}/balance:
    get:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      security:
      - ApiKeyAuth: []
      summary: Find Balance Account By ID
      tags:
      - Accounts
  /v1/accounts/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
      security:
      - ApiKeyAuth: []
      summary: Delete Account By ID
      tags:
      - Accounts
  /v1/charity-mrys:
    post:
      consumes:
      - application/json
      description: Create Charity Mrys
      parameters:
      - description: Create charity mrys
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.CharityMrys'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.CharityMrys'
      summary: Create Charity Mrys
      tags:
      - CharityMrys
  /v1/charity-mrys/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Charity Mrys ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: boolean
      security:
      - ApiKeyAuth: []
      summary: Delete One Charity Mrys By ID
      tags:
      - CharityMrys
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CharityMrys'
      security:
      - ApiKeyAuth: []
      summary: Find One Charity Mrys By ID
      tags:
      - CharityMrys
    patch:
      consumes:
      - application/json
      description: Update Charity Mrys By ID
      parameters:
      - description: Update charity mrys
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/domain.CharityMrys'
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.CharityMrys'
      summary: Update Charity Mrys By ID
      tags:
      - CharityMrys
  /v1/charity-mrys/create-bulk:
    post:
      consumes:
      - application/json
      description: Create Bulk Charity Mrys
      parameters:
      - description: Create charity mrys
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/usecase.CreateBulkCharityMrysInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/domain.CharityMrys'
            type: array
      summary: Create Bulk Charity Mrys
      tags:
      - CharityMrys
  /v1/charity-mrys/list-all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.CharityMrys'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Find All CharityMrys
      tags:
      - CharityMrys
  /v1/charity-mrys/list-pagination/{currentPage}/{perPage}/{sort}:
    get:
      consumes:
      - application/json
      parameters:
      - description: CurrentPage
        in: path
        name: currentPage
        required: true
        type: integer
      - description: PerPage
        in: path
        name: perPage
        required: true
        type: integer
      - description: Sort
        in: path
        name: sort
        required: true
        type: string
      - description: Search
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CharityMrysPagination'
      security:
      - ApiKeyAuth: []
      summary: Find Pagination CharityMrys
      tags:
      - CharityMrys
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
